---
features: 4
patience: 150
dropout: 0.35
reg: 0.0000001
eps_thres: 1.0e-13
dataset: zara01_shifted
dataset_path: ../datasets/UCY/zara01
#dataset: cocktail_party
#dataset_path: "../datasets/cocktail_party"
