---
features: 4
patience: 150
dropout: 0.35
reg: 0.0000001
eps_thres: 1.0e-13
dataset: hotel_shifted
dataset_path: ../datasets/ETH/seq_hotel
#dataset: cocktail_party
#dataset_path: "../datasets/cocktail_party"
